### ISSUE TITLE
Worker Pod configuration

### ISSUE THREAD

**Issue by mrocklin** [dask/daskernetes#20]
I need to configure my worker pods to have elevated priveleges.  I think that I can do this with the following:

```python
        # code taken from @yuvipanda
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
```

However, this isn't appropriate to add to the basic pod template in this project, so this should probably be made configurable.  I propose the following options to a new keyword, `pod=`

1.  Nothing, in which case we provide our current mechanism
2.  A `kubernetes.client.V1Pod` object
3.  A dictionary spec that we can turn into a `kubernetes.client.V1Pod` object using `kubernetes.client.ApiClient.deserialize`
4.  A filename that we can load with `yaml` to obtain 3

If any of the latter three options are selected then none of the threads/image/etc. options should be set.

**Comment by mrocklin** [comment]
Sadly it appears that I over-estimated the deserialize method

```python
class _FakeResponse(object):
    """ Kubernetes public API expects a response object """
    def __init__(self, data):
        self._data = data

    @property
    def data(self):
        import yaml
        return yaml.dump(self._data)

    
def deserialize_pod(x):
    """ Deserialize object to a Kubernetes V1Pod object
            
    Parameters
    ----------
    x: object
        Either a Pod, a dictionary definition, or a filename to a
        yaml-deserializable definition.

    Returns 
    ------- 
    kubernetes.client.V1Pod
    """     
    if isinstance(x, str):
        import yaml
        with open(x):
            x = yaml.load(x)
    if isinstance(x, dict):
        import pdb; pdb.set_trace()
        x = client.ApiClient().deserialize(_FakeResponse(x), client.V1Pod)
    return x
        
x = {'api_version': None,
 'kind': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': None,
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'labels': {},
              'name': 'foo',
              'namespace': None,
              'owner_references': None,
              'resource_version': None,
              'self_link': None,
              'uid': None},
 'spec': {'active_deadline_seconds': None,
          'affinity': None,
          'automount_service_account_token': None,
          'containers': [{'args': None,
                          'command': None,
                          'env': None,
                          'env_from': None,
                          'image': 'foo:latest',
                          'image_pull_policy': None,
                          'lifecycle': None,
                          'liveness_probe': None,
                          'name': 'dask-worker',
                          'ports': None,
                          'readiness_probe': None,
                          'resources': None,
                          'security_context': None,
                          'stdin': None,
                          'stdin_once': None,
                          'termination_message_path': None,
                          'termination_message_policy': None,
                          'tty': None,
                          'volume_mounts': None,
                          'working_dir': None}],
          'dns_policy': None,
          'host_aliases': None,
          'host_ipc': None,
          'host_network': None,
          'host_pid': None,
          'hostname': None,
          'image_pull_secrets': None,
          'init_containers': None,
          'node_name': None,
          'node_selector': None,
          'priority': None,
          'priority_class_name': None,
          'restart_policy': None,
          'scheduler_name': None,
          'security_context': None,
          'service_account': None,
          'service_account_name': None,
          'subdomain': None,
          'termination_grace_period_seconds': None,
          'tolerations': None,
          'volumes': None},
 'status': None}

>>> client.ApiClient().deserialize(_FakeResponse(x), client.V1Pod)
{'api_version': None,
 'kind': None,
 'metadata': None,
 'spec': None,
 'status': None}
```

**Comment by mrocklin** [comment]
I can still procede here, but we're asking users to create Pod objects with the Python API, which seems less friendly and commonly known than the YAML API.

**Comment by mrocklin** [comment]
Never mind.  I had silly bugs.  See https://github.com/yuvipanda/daskernetes/pull/21

**Comment by yuvipanda** [comment]
We have the same issue in kubespawner and have solved with the following:

1. Provide direct options for most used parameters. These here would be
just param to constructor, in kubespawner these are direct traitlets
2. Add an extra_container_config and extra_pod_config that are useful level
1 escape hatches. These are just arbitrary dicts merged into the pod spec
3. Override a function that generates the pod spec. This is most flexible
and advanced escape hatch.

https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py
shows how all these can be implemented. 2 is
singleuser_extra_container_config and singleuser_extra_pod_config, 3 is
both the make_pod function and the modify_pod_hook.

I do not think yaml should be used here at all, makes things too complex
imo.

**Comment by mrocklin** [comment]
I'm actually way more comfortable with yaml than with the Python kubernetes API which seems fairly verbose.  I would like, for example, to include yaml specs in a `.daskernetes.yaml` file for the workers.  It seems easier to me to move around config files rather than Python code.

**Comment by mrocklin** [comment]
I'm curious about option 2 where you merge a dictionary into an existing spec.  I'm taking a look at `_map_attribute` in objects.py but I'm not sure how attribute_map works.

**Comment by yuvipanda** [comment]
I agree we shouldn't ask users to use the kubernetes API client - that is
indeed cumbersome and only for option 3 not 2.

I also agree that writing config files is a good way to do this, but don't
think those should be in core. Keeping yaml out of the core functionality
of the library feels like the clean thing to do to me.

For longer term, look at kubernetes CustomResourceDefinitions. Having a
daskcluster crd is probably the way to go, and it easily offers a nice
abstraction that can be used from various programming languages as well as
yaml / json.

**Comment by mrocklin** [comment]
Will do, although short term I'm likely to go forward a little bit with specifying a yaml config file on the side and pointing KubeCluster to it.  I'm happy to pursue this in my own branch for the time being.  Hopefully what I produce can be used as a conversation piece to help me understand common practice here.

**Comment by mrocklin** [comment]
We seem to have a decent set of solutions in master for this now.  Closing.
