### ISSUE TITLE
Resolve local testing approach

### ISSUE THREAD

**Issue by mrocklin** [dask/daskernetes#4]
There are a couple options:

1.  Use telepresence like the following:

         telepresence --expose 8786 --run py.test daskernetes

2.  Use ip route as show in the README.  If so we should probably include instructions to reverse these steps

**Comment by yuvipanda** [comment]
README has better instructions now. Can you test it out?

**Comment by yuvipanda** [comment]
@mrocklin can we close this now?

**Comment by mrocklin** [comment]
I'm working on circle-ci now by the way
